TEAM_ABBREVIATIONS_TO_TEAM = {
    'ATL': 'ATLANTA HAWKS',
    'BOS': 'BOSTON CELTICS',
    'BRK': 'BROOKLYN NETS',
    'CHI': 'CHICAGO BULLS',
    'CHO': 'CHARLOTTE HORNETS',
    'CLE': 'CLEVELAND CAVALIERS',
    'DAL': 'DALLAS MAVERICKS',
    'DEN': 'DENVER NUGGETS',
    'DET': 'DETROIT PISTONS',
    'GSW': 'GOLDEN STATE WARRIORS',
    'HOU': 'HOUSTON ROCKETS',
    'IND': 'INDIANA PACERS',
    'LAC': 'LOS ANGELES CLIPPERS',
    'LAL': 'LOS ANGELES LAKERS',
    'MEM': 'MEMPHIS GRIZZLIES',
    'MIA': 'MIAMI HEAT',
    'MIL': 'MILWAUKEE BUCKS',
    'MIN': 'MINNESOTA TIMBERWOLVES',
    'NOP': 'NEW ORLEANS PELICANS',
    'NYK': 'NEW YORK KNICKS',
    'OKC': 'OKLAHOMA CITY THUNDER',
    'ORL': 'ORLANDO MAGIC',
    'PHI': 'PHILADELPHIA 76ERS',
    'PHO': 'PHOENIX SUNS',
    'POR': 'PORTLAND TRAIL BLAZERS',
    'SAC': 'SACRAMENTO KINGS',
    'SAS': 'SAN ANTONIO SPURS',
    'TOR': 'TORONTO RAPTORS',
    'UTA': 'UTAH JAZZ',
    'WAS': 'WASHINGTON WIZARDS',

    # DEPRECATED TEAMS
    'NJN': 'NEW JERSEY NETS',
    'NOH': 'NEW ORLEANS HORNETS',
    'NOK': 'NEW ORLEANS OKLAHOMA CITY HORNETS',
    'CHA': 'CHARLOTTE BOBCATS',
    'CHH': 'CHARLOTTE HORNETS',
    'SEA': 'SEATTLE SUPERSONICS',
    'VAN': 'VANCOUVER GRIZZLIES',
}

players_season_totals_columns = [
    "name",
    "position",
    "age",
    "team",
    "season_end_year",
    "games_played",
    "games_started",
    "minutes_played",
    "made_field_goals",
    "attempted_field_goals",
    "field_goal_percentage",
    "made_three_point_field_goals",
    "attempted_three_point_field_goals",
    "three_point_field_goal_percentage",
    "made_two_point_field_goals",
    "attempted_two_point_field_goals",
    "two_point_field_goal_percentage",
    "effective_field_goal_percentage",
    "made_free_throws",
    "attempted_free_throws",
    "free_throw_percentage",
    "offensive_rebounds",
    "defensive_rebounds",
    "total_rebounds",
    "assists",
    "steals",
    "blocks",
    "turnovers",
    "personal_fouls",
    "points",
    "fantasy_points"
    ]

advanced_players_season_totals_columns = [
    "name",
    "position",
    "age",
    "team",
    "season_end_year",
    "games_played",
    "minutes_played",
    "player_efficiency_rating",
    "true_shooting_percentage",
    "three_point_attempt_rate",
    "free_throw_attempt_rate",
    "offensive_rebound_percentage",
    "defensive_rebound_percentage",
    "total_rebound_percentage",
    "assist_percentage",
    "steal_percentage",
    "block_percentage",
    "turnover_percentage",
    "usage_percentage",
    "offensive_win_shares",
    "defensive_win_shares",
    "win_shares",
    "win_shares_per_48_minutes",
    "offensive_box_plus_minus",
    "defensive_box_plus_minus",
    "box_plus_minus",
    "value_over_replacement_player",
    "fantasy_points"
    ]

players_per_game_stats_columns = [
    "name",
    "position",
    "age",
    "team",
    "season_end_year",
    "games_played",
    "games_started",
    "minutes_played_per_game",
    "field_goals_per_game",
    "field_goal_attempts_per_game",
    "field_goal_percentage",
    "three_point_field_goals_per_game",
    "three_point_field_goal_attempts_per_game",
    "three_point_field_goal_percentage",
    "two_point_field_goals_per_game",
    "two_point_field_goal_attempts_per_game",
    "two_point_field_goal_percentage",
    "effective_field_goal_percentage",
    "free_throws_per_game",
    "free_throw_attempts_per_game",
    "free_throw_percentage",
    "offensive_rebounds_per_game",
    "defensive_rebounds_per_game",
    "total_rebounds_per_game",
    "assists_per_game",
    "steals_per_game",
    "blocks_per_game",
    "turnovers_per_game",
    "personal_fouls_per_game",
    "points_per_game",
    "fantasy_points"
    ]